import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "orval";

const packageRoot = fileURLToPath(new URL(".", import.meta.url));

/**
 * Default: live spec from a running backend (`pnpm dev:backend`).
 * CI / offline: set OPENAPI_FILE=../../openapi.json (root `pnpm gen:contract` does this).
 */
const inputTarget = process.env.OPENAPI_FILE
  ? resolve(packageRoot, process.env.OPENAPI_FILE)
  : "http://localhost:8787/openapi.json";

export default defineConfig({
  ody: {
    input: {
      target: inputTarget,
    },
    output: {
      mode: "tags-split",
      target: "./src/generated/endpoints",
      schemas: "./src/generated/models",
      client: "react-query",
      httpClient: "fetch",
      clean: true,
      prettier: false,
      override: {
        mutator: {
          path: "./src/mutator.ts",
          name: "customFetch",
        },
        header: () => [
          "/**",
          " * @generated by Orval — DO NOT EDIT.",
          " * Regenerate: pnpm gen:contract",
          " */",
        ],
      },
    },
  },
});
